from SimilarityModule import *
import pandas as pd
from similarityHelper import *

class SimilarityModuleTest():

    inputTexts = [
        'give me the total receipts for each affiliation',
        'give me the average of receipts by affiliation',
        'give me the median of receipts by affiliation',
    ]

    expectedOutputs = [
        'SELECT sum( ttl_receipts ) FROM data GROUP_BY pty_affiliation',
        'SELECT average( ttl_receipts ) FROM data GROUP_BY pty_affiliation',
        'SELECT median( ttl_receipts ) FROM data GROUP_BY pty_affiliation'
    ]

    def __init__( self ):
        print("Initialize Module")

    # Helper function to test SQL queries generated by the SimilarityModule
    def testSimilarityModule( self ):
        idx = 0
        df  = readDf("data\cand_summary.txt", delimiter = "|")
        sm  = SimilarityModule(df.columns, 'data')
        for inputText in SimilarityModuleTest.inputTexts:
            actualOutput = sm.SQLSuggestion( inputText )
            print('Testing input ', inputText, '...')
            if( actualOutput.lower() == SimilarityModuleTest.expectedOutputs[idx].lower() ):
                idx+=1
                print('Test Passed!')
            else:
                print('Test Failed')

if __name__ == "__main__":
    smt = SimilarityModuleTest()
    smt.testSimilarityModule()